apiVersion: v1
kind: Service
metadata:
  name: kraken-cluster-aqmp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kraken-cluster
  ports:
    - port: 5672
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5672
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30000