apiVersion: v1
data:
  default_user.conf: ZGVmYXVsdF91c2VyID0gcnVzdF9wcm9kdWNlcgpkZWZhdWx0X3Bhc3MgPSBCb3ZpbmU5
  host: a3Jha2VuLWNsdXN0ZXIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  password: Qm92aW5lOQ==
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: cnVzdF9wcm9kdWNlcg==
kind: Secret
metadata:
  name: my-secret 
type: Opaque
