apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: kraken-cluster
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 6Gi
    limits:
      cpu: 1000m
      memory: 6Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_mqtt
      - rabbitmq_web_mqtt
      - rabbitmq_stomp
      - rabbitmq_web_stomp
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_amqp1_0
  persistence:
    storageClassName: longhorn
    storage: "100Gi"
